server:
  port: 9000

spring:
  application:
    name: cryptex-simple

  datasource:
    url: jdbc:mysql://localhost:3306/cryptex_simple
    username: ${database.mysql_username}
    password: ${database.mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  config:
    import: optional:classpath:secret.properties

atonic:
  cryptex:
    jwtSecret: ${jwt.jwt_secret}
    jwtExpirationMs: 86400000
